name: Ejecucion ETL Medallion Medianoche

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-silver-layer:
    runs-on: ubuntu-latest
    steps:
      - name: Instalar cliente PostgreSQL 16
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client-16

      - name: Esperar que el pooler se estabilice
        run: sleep 60

      - name: Ejecutar SP de Estudiantes
        env:
          PGPASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          for i in 1 2 3 4 5; do
            echo "Intento $i de sp_load_estudiantes..."
            psql "host=aws-1-us-east-2.pooler.supabase.com port=6543 dbname=postgres user=postgres.xjzcfiusbhrvcbfpqqbz sslmode=require connect_timeout=30" \
              -c "SELECT silver.sp_load_estudiantes();" && echo "OK" && break
            echo "Fallo, esperando 30s..."
            sleep 30
          done

      - name: Ejecutar SP de Matriculas
        env:
          PGPASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          for i in 1 2 3 4 5; do
            echo "Intento $i de sp_load_matriculas..."
            psql "host=aws-1-us-east-2.pooler.supabase.com port=6543 dbname=postgres user=postgres.xjzcfiusbhrvcbfpqqbz sslmode=require connect_timeout=30" \
              -c "SELECT silver.sp_load_matriculas();" && echo "OK" && break
            echo "Fallo, esperando 30s..."
            sleep 30
          done