name: Ejecucion ETL Medallion Medianoche

on:
  schedule:
    - cron: '0 0 * * *' # Se ejecuta a la medianoche UTC
  workflow_dispatch: # Botón para ejecutarlo manualmente

jobs:
  update-silver-layer:
    runs-on: ubuntu-latest
    steps:
      - name: Instalar cliente PostgreSQL
        run: sudo apt-get install -y postgresql-client

      - name: Ejecutar SP de Estudiantes y Matriculas
        env:
          DB_URL: ${{ secrets.DB_URL }}
          PGPASSWORD: ${{ secrets.DB_PASSWORD }} # GitHub usará esto automáticamente
        run: |
          psql "$DB_URL" -c "SELECT silver.sp_load_estudiantes();"
          psql "$DB_URL" -c "SELECT silver.sp_load_matriculas();"